name: drive_note_app
description: A Google Drive connected notes app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_riverpod: ^2.3.6
  
  # Navigation
  go_router: ^10.0.0
  
  # Network
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  
  # Storage
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.1.1
  
  # Google APIs
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  google_sign_in: ^6.1.4
  url_launcher: ^6.1.12
  
  # JSON Serialization
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  
  # UI
  flutter_markdown: ^0.6.17
  shimmer: ^3.0.0
  
  # Utils
  uuid: ^3.0.7
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/